### ISSUE TITLE
关于bbr的设置

### ISSUE THREAD

**Issue by kirbyzhu** [letssudormrf/ssr-bbr-docker#1]
请问在dockerfile里面哪个地方是开通bbr的？
还是debian：latest的镜像里面已经包含bbr的内核升级？或者是rinetd里面集成了？

谢谢解答！

**Comment by letssudormrf** [comment]
是rinetd集成了lkl,lkl内核是带bbr加速.
现在准备更新一下dockerfile,把rinetd换成增强版bbr内核.

**Comment by kirbyzhu** [comment]
@letssudormrf 谢谢解答！
